// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx-sD1Jck8XSJe7gznzlDYGL5tx5q6tU4',
    appId: '1:358089542646:web:6d6ebf7773af80743255d7',
    messagingSenderId: '358089542646',
    projectId: 'toggleapp-30e9b',
    authDomain: 'toggleapp-30e9b.firebaseapp.com',
    storageBucket: 'toggleapp-30e9b.firebasestorage.app',
    measurementId: 'G-DBV7VDW5KH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB31Q4GY5PwZUAAZqLZ4xnex4AxPPkudgU',
    appId: '1:358089542646:android:5bee497dc0924b9f3255d7',
    messagingSenderId: '358089542646',
    projectId: 'toggleapp-30e9b',
    storageBucket: 'toggleapp-30e9b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx-sD1Jck8XSJe7gznzlDYGL5tx5q6tU4',
    appId: '1:358089542646:web:5ff08903192b63623255d7',
    messagingSenderId: '358089542646',
    projectId: 'toggleapp-30e9b',
    authDomain: 'toggleapp-30e9b.firebaseapp.com',
    storageBucket: 'toggleapp-30e9b.firebasestorage.app',
    measurementId: 'G-NBC57Z1KMG',
  );

}